Rsvp
SHPEUCF/shpeucfbackend pull request #19
Opened 2020-09-09 23:29 UTC by jeffjramos21

Fixed rsvp to correctly update rsvp array when adding a new user to it. Added 404 error messages for when we try to access an event or user document that does not exist.

2020-09-11 08:07 UTC, HanielDiaz requested changes
Please download the linter and fix all the linting errors.

2020-09-12 15:46 UTC, idelmr requested changes
Minor changes

2020-09-12 15:46 UTC, idelmr commented on functions/src/Controller/Event.ts
> +	else if (!validEvent && ! validUser) {
Remove space after `!`

2020-09-12 15:46 UTC, idelmr commented on functions/src/Controller/Event.ts
> +	else if (!validEvent && ! validUser) {
Remove space after `!`

2020-09-12 15:46 UTC, idelmr commented on functions/src/Controller/Event.ts
> +
Remove empty  line

2020-09-12 15:46 UTC, idelmr commented on functions/src/Controller/Event.ts
> +
Remove empty line

2020-09-12 15:46 UTC, idelmr commented on functions/src/Controller/Event.ts
> +
Remove line

2020-09-12 15:46 UTC, idelmr commented on functions/src/Controller/Event.ts
> +
Also remove empty lines between variable declarations

2020-09-12 20:45 UTC, HanielDiaz requested changes

2020-09-12 20:45 UTC, HanielDiaz commented on functions/src/Controller/Event.ts
> +		response.status(200).send('Error 404: Event document not found\nError 404: User document not found');
no. 404 is a status code. so don't send status 200. same for below

2020-09-12 20:45 UTC, HanielDiaz commented on functions/src/Controller/Event.ts
> +		response.status(200).send('Error 404: Event document not found\nError 404: User document not found');
status should be 404 not 200 same for below

2020-09-12 20:45 UTC, HanielDiaz commented on functions/src/Controller/Event.ts
> +			response.status(200).send('Error 404: Event document not found');
status 404

2020-09-13 00:49 UTC, HanielDiaz approved these changes
lgtm

2020-09-13 13:20 UTC, idelmr approved these changes

2020-09-14 01:35 UTC, merged