added edit committee feature.
SHPEUCF/shpeucfbackend pull request #36
Opened 2020-10-07 05:18 UTC by PromAtlas

Fixes #34 

## Description

I added the edit committee feature, which looks at an existing document and changes the title,
chair, events, and description of the committee respectively. You input the oldTitle of the committee in addition
to the updated committee attributes.

## Types of changes

- [ ] Bug fix (non-breaking change that fixes an issue)
- [X ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other 

## Checklist:

- [X ] My code follows the code style of this project found on [ESLint](../functions/.eslintrc.yml).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-12 06:10 UTC, smontana30 approved these changes

2020-10-18 18:12 UTC, BautistaBertolami approved these changes

2020-10-18 22:44 UTC, jeffjramos21 requested changes
fix merge conflicts

2020-10-19 01:28 UTC, PromAtlas commented
To fix the merge conflicts, we needed to change how deleteCommittee works, it now also searches for the id rather than the title.

2020-10-19 02:42 UTC, jeffjramos21 approved these changes

2020-10-19 02:43 UTC, merged